name: PR test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: show info
        run: |
          echo "RUNNING"
          whoami
          bash x.sh
